### PR TITLE
Enhance python2/3 support

### PR DESCRIPTION
**Pull request by john-westcott-iv**
### What does this PR do?
- This PR incorporates additional imports from ansible.module_utils.six.moves to make the modules work with either python2 or python3.
- If the existing tests test the error conditions (i.e. catching the HTTPExceptions) no additional tests should be required. Please note, I performed py_compile and flake8 tests against the modules but I do not have an instance of CyberArk stood up to run the playbooks in the tests directory. These tests were run against: ansible 2.10.8 and ansible 2.9.18 with python versions 3.9.2 and 2.7.16
- There are no relevant screen shots with this PR.

### What ticket does this PR close?
Resolves None

#### Change log
- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [X] The changes in this PR do not require tests

#### Documentation
- [X] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

### CODE REVIEW

**Comment by jeffrechten** [comment]
Reviewed. LGTM.

**Comment by jeffrechten** [comment]
@JimmyJamCABD  please see this PR. Thanks.

**Review by infamousjoeg — APPROVED** [review]
Looks good to me -- definitely cleans the code and reduces import overhead. No code logic changes within.

**Comment by infamousjoeg** [comment]
@JimmyJamCABD @cyberark-bizdev I will add that if this PR is merged, the Python version 2 commit should be deprecated as this solves version compatibility for both.

**Review by JimmyJamCABD — APPROVED** [review]

**Pull request merged**
